language: node_js
node_js:
- '8.10'
cache:
  directories:
  - node_modules
install:
- yarn install
script:
- yarn test
notifications:
  slack:
    secure: bKPjvJ7QdhJOGNwMFH6d4PgAjuFEMO70zbo6rVqYBLPexgRlnqzq7wG67DrxHO4b4sUVbFRNPa36WQZwsbECRTllRNxoUl38Hr9cOXWCJEnun/R3TC4TIwUuXVBWdvQ9jc6XpOxE5TmVnYgugqzPHFn84re+DZjasZ0XgIVl4eZZz+wVOVw9ffiXxsBDJ0z9fnhanG8KY/xsPTqMxHc+LiroO0+y1QH3+lrGB/WRQMrDiQk8lBTlflByD5lj+meWVlYHGtoTblZrVdVB3RCGUTkxS0U33vR97980V7PfWjdfeI2/aHx0hpafb/Om3P1ixBYl56Fhr9KCTepapv1FhVfpzkVlLlrEMHZG3Uj0cdKzawxR2zYsT9qQvMJ2K/vKH/3t1zsqlDWRZoMwkqdvkt4YKIqZKfwkbOJdpxXz02AdzA0T5lEUc8nj/dOKqTQbpk6FEOo1DA+gZLX2r5AhHq77vzWgmSF6TPCV+EnrSC/ikypnIh8HPbuc/Qnylny8J9BJhNjHh6527tj9U7Bw67Gjp04UdZMEorNvGMvSQpBJu0rQnWRMe+khdrwOmoA+QhdDmofzx4TR7ytSJCPbrCFEu+CkNQQzxTXnhj4eBwRGwNNs6xDJBan1liW/3cx122mYwAvSr5lWzwsFN+arlDXgiEygBhFWt3rY9l2iVsY=
