language: node_js
node_js:
  - "8.10"
cache:
  directories:
    - node_modules
install:
  - yarn install
script:
  - yarn test
notifications:
  slack:
    secure: lf+KzsCFCF82ZEz7m1wZprUl00LCH+LYd1mybpjguG2ot6OIlhgtI07QpFHR4/cQIuSfIeDlENvnCaHhuFpzoKNtX2euvTKnPsGC7DpFaVsBQn3YmXPLB7nJEZQ/i4Dtd6U68WY5pbUvWoCBwuqstuGzDEauimqYBMfGF9DTzqQOrGLLibvav/hNm1C1fv4Ge/8IDHaqOsCq5gDRm7tvhL0+zB7SX6szzIF9DT2dwy3BfxJXzZg9/+C+1rb8Nca/Tvvj3uqLD/C3I9WxT8Zrgb+o756Qsb3YzUNREbZgjCGPq5tw/ys/7R6Ml8A3E43emYFjADyXlLMzKNJ3Y/bO745CvUkzA3QgMF/2Xqhdn9PbJ1D1HUKjzVvQ3xGRM2JbAjaJI+5rOJuujGaEU6Ok/5Dvp/di6fdrBlCxfGiPJXUeDOtE9HaTZSuG0VovVrYhjrX01y15byyGnYIxC7FTaXjc6mgAfXXTBjQkswL1LKpafzKsWtdHPrx/JN0J/fhLkhh5MY/XlmpDlyccOZ1lBkGrzOWjEpNptAbjO6L8mGBgtqBFW+ubnOXkXUkppy7VWQk+XO+6zLAF1e/SEsgciieBOtixmFAyLnPMI6S7el76Nf8vkAXe9PAF37vzamz8vHq2EJbvsuixDfvoj/qJj7IxiPc6MLaIcCOsiigjE6o=
